name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: '10.11.0'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Print environment variables
      run: |
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}"
        echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}"
        echo "NEXT_GITHUB_ID=${{ secrets.NEXT_GITHUB_ID }}"
        echo "NEXT_GITHUB_SECRET=${{ secrets.NEXT_GITHUB_SECRET }}"
        echo "NEXT_PUBLIC_PACKAGE_ID=${{ secrets.NEXT_PUBLIC_PACKAGE_ID }}"
        echo "NEXT_PUBLIC_ACCOUNT_BOOK_ID=${{ secrets.NEXT_PUBLIC_ACCOUNT_BOOK_ID }}"
        echo "NEXT_PUBLIC_NETWORK=${{ secrets.NEXT_PUBLIC_NETWORK }}"
        echo "SITE_BUILDER=${{ secrets.SITE_BUILDER }}"

    - name: Build application
      run: pnpm build
      env:
        NODE_ENV: production
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        NEXT_GITHUB_ID: ${{ secrets.NEXT_GITHUB_ID }}
        NEXT_GITHUB_SECRET: ${{ secrets.NEXT_GITHUB_SECRET }}
        WALLET_KEY: ${{ secrets.WALLET_KEY }}
        NEXT_PUBLIC_PACKAGE_ID: ${{ secrets.NEXT_PUBLIC_PACKAGE_ID }}
        NEXT_PUBLIC_ACCOUNT_BOOK_ID: ${{ secrets.NEXT_PUBLIC_ACCOUNT_BOOK_ID }}
        NEXT_PUBLIC_NETWORK: ${{ secrets.NEXT_PUBLIC_NETWORK }}

    - name: Create deployment package
      run: |
        tar -czf deploy.tar.gz .next public package.json pnpm-lock.yaml

    - name: Deploy to Ubuntu server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "deploy.tar.gz"
        target: "/root/projects/wal0-app"

    - name: Install and Start application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /root/projects/wal0-app
          tar -xzf deploy.tar.gz
          rm deploy.tar.gz
          if [ ! -d "node_modules" ] || [ ! -f "node_modules/.pnpm/lock.yaml" ]; then
            pnpm install --prod
          fi
          pm2 restart wal0 || pm2 start "pnpm start" --name wal0
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        NEXT_GITHUB_ID: ${{ secrets.NEXT_GITHUB_ID }}
        NEXT_GITHUB_SECRET: ${{ secrets.NEXT_GITHUB_SECRET }}
        WALLET_KEY: ${{ secrets.WALLET_KEY }}
        NEXT_PUBLIC_PACKAGE_ID: ${{ secrets.NEXT_PUBLIC_PACKAGE_ID }}
        NEXT_PUBLIC_ACCOUNT_BOOK_ID: ${{ secrets.NEXT_PUBLIC_ACCOUNT_BOOK_ID }}
        NEXT_PUBLIC_NETWORK: ${{ secrets.NEXT_PUBLIC_NETWORK }}